apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sample-extension-dotnet-minimalapi
  name: sample-extension-dotnet-minimalapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-extension-dotnet-minimalapi
  strategy: {}
  template:
    metadata:
      labels:
        app: sample-extension-dotnet-minimalapi
    spec:
      containers:
      - image: <YOUR DOCKER ID>/dotnet6minimalapi:0.0.1
        name: sample-extension-dotnet-minimalapi
        imagePullPolicy: Always
        resources: {}
        ports:
        - containerPort: 80
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: sample-extension-dotnet-minimalapi
  name: sample-extension-dotnet-minimalapi
spec:
  ports:
  - port: 5046
    protocol: TCP
    targetPort: 80
  selector:
    app: sample-extension-dotnet-minimalapi
  type: ClusterIP
status:
  loadBalancer: {}
